version: "3.8"

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  api:
    build: ./api/.
    volumes:
      - ./api/src:/api/src
#    ports:
#      - "3050:3050"
  www:
    build: ./www/.
    volumes:
      - ./www/src:/www/src
#    ports:
#      - "8080:3000"

volumes:
  caddy_data:
  caddy_config: